# Setup
title:            'blog jagung letup'
tagline:          'padahal aku sukanya keripik jagung'
description:      'Isi dari blog ini tidak membahas tentang jagung.'
url:              ''
baseurl:          '/blog'

# About and contact
author:
  name:           'Dani'

# Gems
plugins:
  - jekyll-gist

# Custom vars
version:          3.0.0
